// Start here: replace the sample recipient, memories, interests and messages.
window.BIRTHDAY_SITE = {
  meta: {
    title: "生日奇想剧场",
    description: "一个可定制的生日祝福互动网页。",
  },
  recipient: {
    name: "小星",
    age: 18,
    birthdayDate: "2027-01-01",
  },
  // Keep this true while editing. Set it to false before publishing a timed surprise.
  previewMode: true,
  hero: {
    cakeMessage: "生日快乐！",
    floatingWishes: ["平安喜乐", "万事胜意", "灵感常在", "亲友顺遂", "好梦成真"],
  },
  photos: [
    {
      date: "某个春日",
      location: "一起出发",
      title: "第一次收藏的瞬间",
      note: "把这里换成照片背后的故事，也可以只留一句轻松的祝福。",
      image: "./assets/illustrations/memory-cake.svg",
      alt: "插画：星光下的生日蛋糕",
      cardClass: "tilt-left",
      tapeClass: "tape-left",
      sticker: "✦",
    },
    {
      date: "一个夏夜",
      location: "沿途风景",
      title: "值得反复想起的一天",
      note: "示例内容不包含真实人物、地点或经历，发布前可按需替换。",
      image: "./assets/illustrations/memory-balloons.svg",
      alt: "插画：蓝色与珊瑚色气球",
      cardClass: "lift-up",
      tapeClass: "tape-right",
      sticker: "♪",
    },
    {
      date: "晴朗周末",
      location: "好事发生",
      title: "收到惊喜的时刻",
      note: "照片、日期、地点与说明都集中在这个配置文件里。",
      image: "./assets/illustrations/memory-gift.svg",
      alt: "插画：装着星光的礼物盒",
      cardClass: "tilt-right",
      tapeClass: "tape-center",
      sticker: "☁",
    },
    {
      date: "下一段旅程",
      location: "未完待续",
      title: "留给未来的新回忆",
      note: "也可以删掉任意一项，相册会自动适应剩余内容。",
      image: "./assets/illustrations/memory-night.svg",
      alt: "插画：月亮、星星与远山",
      cardClass: "tilt-left wide-frame",
      tapeClass: "tape-double",
      sticker: "☾",
    },
  ],
  interests: [
    {
      key: "musical",
      label: "音乐剧",
      title: "聚光灯为你亮起",
      theme: "musical",
      planetClass: "planet-musical",
      image: "./assets/illustrations/interest-universe.svg",
      imageAlt: "兴趣宇宙示例插画",
      wishes: ["愿每一次登场都从容坚定。", "愿新的故事里，总有掌声与知己。"],
    },
    {
      key: "time",
      label: "时间旅行",
      title: "下一站是好天气",
      theme: "time",
      planetClass: "planet-time",
      image: "./assets/illustrations/interest-universe.svg",
      imageAlt: "兴趣宇宙示例插画",
      wishes: ["愿过去沉淀成勇气，未来保留着惊喜。", "愿每个新章节都值得期待。"],
    },
    {
      key: "puzzle",
      label: "解谜游戏",
      title: "所有线索通向好运",
      theme: "puzzle",
      planetClass: "planet-puzzle",
      image: "./assets/illustrations/interest-universe.svg",
      imageAlt: "兴趣宇宙示例插画",
      wishes: ["愿难题都有答案，选择都通往喜欢的结局。"],
    },
    {
      key: "fantasy",
      label: "奇幻故事",
      title: "星火一路相伴",
      theme: "fantasy",
      planetClass: "planet-fantasy",
      image: "./assets/illustrations/interest-universe.svg",
      imageAlt: "兴趣宇宙示例插画",
      wishes: ["愿你始终追随自己的心意。", "愿旅途之中，一直有光。"],
    },
    {
      key: "radio",
      label: "夜间电台",
      title: "月光替你留灯",
      theme: "radio",
      planetClass: "planet-radio",
      image: "./assets/illustrations/interest-universe.svg",
      imageAlt: "兴趣宇宙示例插画",
      wishes: ["愿你穿过夜色时，知道前面总有一盏灯。", "今晚的月光只负责让你开心。"],
    },
  ],
  gachaBlessings: [
    {
      rarity: "★★★★★",
      tier: "blue",
      title: "好运值 +100%",
      body: "今天出门、许愿、点击按钮，统统有加成。",
      signature: "生日剧场：这张请优先给寿星。",
    },
    {
      rarity: "★★★★★",
      tier: "blue",
      title: "睡眠质量 +20%",
      body: "今晚做的梦会很轻，醒来也会带一点好心情。",
      signature: "温柔生效，不设期限。",
    },
    {
      rarity: "★★★★★★",
      tier: "gold",
      title: "今日开心保底",
      body: "无论今天发生什么，快乐都会在结尾准时结算。",
      signature: "此卡建议立即生效。",
    },
    {
      rarity: "★★★★★★",
      tier: "gold",
      title: "今天的你绝对主角",
      body: "剧情自动把镜头切给你，背景音乐也更偏爱一点。",
      signature: "主角位已锁定，请放心登场。",
    },
  ],
  letter: {
    label: "一封生日来信",
    lines: [
      "想送你一份可以亲手打开、慢慢探索的生日礼物。",
      "于是我把祝福做成了这一座小小的线上剧场。",
      "愿新一岁的日常有光，重要的人都在身旁。",
      "生日快乐，平安喜乐。",
    ],
  },
  finale: {
    title: "愿你的新一岁，有好故事，也有好天气。",
    body: "下面的星云可以拖动浏览；手势互动仅会在你主动开启后申请摄像头权限。",
    saturnMessage: "人与人的相遇，是许多微小偶然共同写成的奇迹。很高兴在这个宇宙里认识你。",
  },
  ambientWishes: [
    "好运已送达",
    "今晚你是主角",
    "愿望正在发光",
    "生日快乐",
    "新一岁闪闪发亮",
    "故事会偏爱你",
  ],
};
